apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-registry
spec:
  selector:
    matchLabels:
        app: service-registry
  serviceName: service-registry
  replicas: 2
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: borissolomonia/dailycodebuffer:service-registry
        ports:
        - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: service-registry-headless
spec:
  clusterIP: None
  selector:
    app: service-registry
  ports:
    - port: 8761
      name: service-registry

---

apiVersion: v1
kind: Service
metadata:
  name: service-registry-nodeport
spec:
  type: NodePort
  selector:
    app: service-registry
  ports:
    - port: 80
      targetPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
      targetPort: 8761

